name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rsync to Hostinger
        uses: burnett01/rsync-deployments@5.4.0
        with:
          switches: -avzr --delete --exclude='.git' --exclude='.github' --exclude='node_modules'
          path: ./
          remote_path: /home/u358740591/public_html
          remote_host: ${{ secrets.HOSTINGER_IP }}
          remote_user: ${{ secrets.HOSTINGER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
